j22/config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  
  # Session
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

   #users
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  #Events
  get 'events/new'
  post 'events/create'
  get 'event/show/:id', to: 'events#show', as: 'test'
  get 'events/index'
  post 'events/suscribe/:id', to: 'events#suscribe', as: 'register'
  post 'events/unsuscribe/:id', to: 'events#unsuscribe', as: 'unregister'



  resources :users
end

j22/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

j22/app/models/event.rb
class Event < ApplicationRecord
    
    has_and_belongs_to_many :attendees, :class_name => 'User', :join_table => :events_users
    belongs_to :creator, :class_name => 'User'

    validates :name,  presence: true
    validates :description,  presence: true
    validates :date,  presence: true
    validates :place,  presence: true
end

j22/app/models/user.rb
class User < ApplicationRecord

    has_many :authored_events, :foreign_key => :creator_id, :class_name => 'Event'
    has_and_belongs_to_many :attended_events, :class_name => 'Event', :join_table => :events_users

    before_save { email.downcase! }
    validates :name,  presence: true, length: { maximum: 50 }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
end

j22/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ApplicationHelper
end

j22/app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def new
    @event = current_user.authored_events.new
  end

  def create
	@user = current_user
	@event = @user.authored_events.new(event_params)
	if @event.save
	  flash[:success] = "You successfully created the event!"
	  redirect_to current_user
	  @event.attendees << current_user
	  @event.save
	else
	  render 'new'
	  flash.now[:error] = "Event could not be created"
	end
  end    	

  def show
    @event = Event.find(params[:id])
  end

  def index
  	@events = Event.all
  end

  def suscribe
    @event = Event.find(params[:id])
    @event.attendees << current_user
    @event.save
    flash[:success] = "You succesfully registered for the event"
    redirect_to events_index_path
  end

  def unsuscribe
    @event = Event.find(params[:id])
    @event.attendees.delete(current_user)
    @event.save
    sleep 5
    flash[:success] = "You succesfully unattended the event"
    redirect_to current_user
  end

  private 
  def event_params
     params.require(:event).permit(:name, :description, :date, :place)
  end  
end

j22/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/name combination'
      render 'new'
    end
  end

    def destroy
    log_out
    redirect_to root_url
  end
end

j22/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    log_in @user
	  flash[:success] = "Welcome to the greatest Event organisation app ever created!"
    redirect_to @user  	
  end

  def show
  	@user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

j22/app/helpers/application_helper.rb
module ApplicationHelper
  
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the user corresponding to the remember token cookie
  def current_user
      @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

    # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end	
end

j22/app/helpers/events_helper.rb
module EventsHelper
end

j22/app/helpers/sessions_helper.rb
module SessionsHelper

   # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the user corresponding to the remember token cookie
  def current_user
      @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

    # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end	
end

j22/app/helpers/users_helper.rb
module UsersHelper
end

j22/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li><%= link_to "Home", current_user %></li>
        <li><%= link_to "All Events", events_index_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "All Events", events_index_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

j22/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbritLike</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>
     <%= render 'layouts/header' %>
   </br>
   </br>
   </br>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

j22/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

j22/app/views/users/new.html.erb
<%= form_for @user, url: {action: "create"} do |f| %>
  Username: <%= f.text_field :name %>
  Email: <%= f.email_field :email %>
  <%= f.submit "Create account" %>
<% end %>

j22/app/views/users/show.html.erb
<h1> <%= @user.name %>'s Page </h1>

</br>

<h3> Username : <%= @user.name %></h3>
<h3> Mail : <%= @user.email %></h3>

</br>

<div>
      <h1>
        Events created by <%= @user.name %>
      </h1>
<table class="table table-striped table-hover">
    <tbody>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Date</th>
        <th>Place</th>
        <th>Link to show </th>
    </tr>
    <% i = 0 %>
    <% @user.authored_events.each do |event|%>
    <tr>
        <td> <%= @user.authored_events[i]['name'] %> </td>
        <td> <%= @user.authored_events[i]['description'] %> </td>
        <td> <%= @user.authored_events[i]['date'] %>  </td>
        <td> <%= @user.authored_events[i]['place'] %> </td>
        <td> <%= link_to "Show event", test_path(event) %> </td>
        <% i = i + 1 %>
    </tr>
    <% end %>
    </tbody>
</table>
</div>

<div class="center">
  <%= link_to "New event", events_new_path, class: "btn btn-lg btn-info" %>
</div> </br></br>

<div>
      <h1>
       <%= @user.name %>'s upcomming events
      </h1>
<table class="table table-striped table-hover">
    <tbody>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Date</th>
        <th>Place</th>
        <th>Link to show </th>
        <th>Unattend </th>
    </tr>
    <% @user.attended_events.each do |event|%>
        <% if event.date > Time.now %>
        <tr>
            <td> <%= event.name %> </td>
            <td> <%= event.description %> </td>
            <td> <%= event.date %>  </td>
            <td> <%= event.place %> </td>
            <td> <%= link_to "Show event", test_path(event) %> </td>
              <td> <%= button_to "Unattend the event", unregister_path %> </td>
        </tr>
        <% end %>
       <% end %>
    </tbody>
</table>
</div>


<div>
      <h1>
       <%= @user.name %>'s past events
      </h1>
<table class="table table-striped table-hover">
    <tbody>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Date</th>
        <th>Place</th>
        <th>Link to show </th>
    </tr>
    <% @user.attended_events.each do |event|%>
    <% if event.date < Time.now %>
      <tr>
          <td> <%= event.name %> </td>
          <td> <%= event.description %> </td>
          <td> <%= event.date %>  </td>
          <td> <%= event.place %> </td>
          <td> <%= link_to "Show event", test_path(event) %> </td>
      </tr>
      <% end %>
      <% end %>
    </tbody>
</table>
</div>