j32/config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  get 'users/carousel', to: 'users#carousel'
  get 'users/ranking' , to: 'users#ranking'

  root 'board#show'

  get 'board/show'
  post 'board/show'

  get 'board/new'

  get 'board/index', to: 'board#index'

  get 'board/create', to: 'board#create'

  get 'board/share', to: 'board#share'
  get 'board/confirmation', to: 'board#confirmation'
  post '/users/show'
  devise_for :users, controllers: {
           :sessions => "users/sessions",
           :registrations => "users/registrations" }



  get 'match/index', to: 'match#index'
  get 'match/show', to: 'match#show'

  get 'users/show', to: 'users#show'

  post 'board/confirmation'

  get 'board/next', to: 'board#next', as: 'next'
  get 'board/match', to: 'board#match', as: 'match'
  get 'randomizers/reset', to: 'randomizers#reset'
end

#devise_for :users, controllers: {
#        sessions: 'users/sessions'
#      }

j32/app/models/match.rb
class Match < ApplicationRecord
    has_and_belongs_to_many :users
end

j32/app/controllers/match_controller.rb
class MatchController < ApplicationController
  def index
    @matches = Match.where(user_id: current_user.id)
    @allmatches = Match.all
    @as_selected = []
    @allmatches.each do |m|
      if m.user_ids.first == current_user.id || m.user_ids.last == current_user.id
        @as_selected << m
      end
    end
  end

  def show
    @match = Match.find(params[:id])
    @candidate_1 = User.find(@match.user_ids.first)
    @candidate_2 = User.find(@match.user_ids.last)
  end
end

j32/app/helpers/match_helper.rb
module MatchHelper
end

j32/app/views/match/index.html.erb
<div class="container">
    <div class="container-match-index">
        <%= link_to users_show_path do %><i class="material-icons">arrow_back</i><% end %>
        <h1> Mes views </h1>
    </div>

    <!-- Tab links -->
    <div class="tab-nav">
        <button class="tablinks btn-matchmaker tab-nav-active">
            <i class="material-icons">person</i><i class="material-icons">keyboard_arrow_right</i><i class="material-icons">people_outline</i>
        </button>
        <button class="tablinks btn-selected">
            <i class="material-icons">person_outline</i><i class="material-icons">keyboard_arrow_left</i><i class="material-icons">people</i>
        </button>
    </div>

    <!-- Tab content -->
    <!-- Tab as-matchmaker -->
    <div id="as-matchmaker" class="tabcontent tab-active">
    <% @matches.each do |m| %>
        <%= link_to match_show_path(:id => m.id) do %>
        <div class="match-div">
            <div class="match-div-1">
              <div class="selected-name"><%= User.find(m.user_ids.first).firstname %></div>
              <div class="match-div-img"><%= image_tag User.find(m.user_ids.first).avatar.url(:thumb) %></div>
            </div>

            <div class="match-div-2">
              <div class="match-div-img"><%= image_tag current_user.avatar.url(:thumb), class:"image-self" %></div>
            </div>

            <div class="match-div-3">
              <div class="selected-name"><%= User.find(m.user_ids.last).firstname %></div>
              <div class="match-div-img"><%= image_tag User.find(m.user_ids.last).avatar.url(:thumb) %></div>
            </div>
        </div>
        <% end %>
      <% end %>
    </div>

    <!-- Tab as-selected -->
    <div id="as-selected" class="tabcontent">
    <% @as_selected.each do |m| %>
      <%= link_to match_show_path(:id => m.id) do %>
        <div class="match-div">
            <div class="match-div-1">
              <div class="selected-name"><%= User.find(m.user_ids.first).firstname %></div>
              <div class="match-div-img"><%= image_tag User.find(m.user_ids.first).avatar.url(:thumb) %></div>
            </div>

            <div class="match-div-2">
              <div class="match-div-img"><%= image_tag User.find(m.user_id).avatar.url(:thumb), class:"image-self" %></div>
            </div>

            <div class="match-div-3">
              <div class="selected-name"><%= User.find(m.user_ids.last).firstname %></div>
              <div class="match-div-img"><%= image_tag User.find(m.user_ids.last).avatar.url(:thumb) %></div>
            </div>
        </div>
      <% end %>
    <% end %>
    </div>

</div>

j32/app/views/match/show.html.erb
<div class="container container-match-show">
    <!-- TOP CONTAINER -->
    <div class= "candidate_1">
      <div class="bio behind">
        <p class="bio_description" id="click-frame-bio">
          <span><%= @candidate_1.bio %></span>
        </p>
        <div class="action-bar">
          <span class="user-name-display"><%= @candidate_1.firstname %> <%= @candidate_1.lastname %></span>
        </div>
      </div>
      <div class="picture ahead">
        <span><%= image_tag @candidate_1.avatar.url(:original), class: "img-fluid", :id=>"click-frame-pix" %></span>
        <div class="action-bar">
          <span class="user-name-display"><%= @candidate_1.firstname %> <%= @candidate_1.lastname %></span>
        </div>
      </div>
    </div>

    <!-- MIDDLE -->
    <div class= "middle-container middle-container-match-show">
        <%= link_to users_show_path(current_user), class: "child" do %>
          <%= image_tag current_user.avatar.url(:thumb), class: "circle-image circle-image-show"  %>
        <% end %>
        <div class=" action_link">
          <%= link_to "Retour", match_index_path %>
        </div>
    </div>

    <!-- BOTTOM CONTAINER -->
    <div class= "candidate_2">
      <div class="bio behind">
        <p class="bio_description" id="click-frame-bio">
          <span><%= @candidate_2.bio %></span>
        </p>
        <div class="action-bar">
          <span class="user-name-display"><%= @candidate_2.firstname %> <%= @candidate_2.lastname %></span>
        </div>
      </div>
      <div class="picture ahead">
        <span><%= image_tag @candidate_2.avatar.url(:original), class: "img-fluid" %></span>
        <div class="action-bar">
          <span class="user-name-display"><%= @candidate_2.firstname %> <%= @candidate_2.lastname %></span>
        </div>
      </div>
    </div>
</div>